# SITE CONFIGURATION
title: Personal Blog # your site title
author: joaomh # You :P
description: > # Meta description of Homepage
  This is my personal blog where I post projects in data science, data engineering, math, or just have fun with programming. Nothing too serious, just having fun :)
url: "https://joaomh.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: João Pinheiro
  links:
    - https://github.com/joaomh
    - https://www.linkedin.com/in/joaomh
    - https://youtube.com/2001engenharia

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/', sym: 'home'}
  - {name: 'About', link: '/about', sym: 'user'}
  - {name: 'Contact', link: '/contact', sym: 'pencil-square-o'}
  - {name: 'Curriculum', link: '/cv', sym: 'home'}

tagline: >
  Data Science - Machine Learning - Robotics - Data Engineering - Programming - Math
#  Modern Jekyll theme focused on speed performance &amp; SEO best practices

hero_img: posts/wallpaper.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: joaomh@protonmail.com # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  joaomh # replace with your_github_username or comment to remove link from footer
youtube_username:  2001engenharia # replace with your_github_username or comment to remove link from footer
linkedin_username:  joaomh # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: joaomh # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-MJLNPGQB # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID
google_analytics: G-LXRVTSHEJR
# Analytics
# analytics:
#   provider               : "google-gtag"
#   google:
#     measurement_id          : "G-LXRVTSHEJR"
#     anonymize_ip         : # true, false (default)

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
